title: Aaron Gelfand
description: This is a website to host my projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-modernist

navigation:
  - text: Home
    url: /
  - text: real_estate_cleaning
    url: /real_estate_cleaning/
